name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: List all files in the current directory
      run: ls -al
    - name: Run tests with pytest and collect coverage
      run: |
        coverage run -m pytest ./Test_calculator.py  # Updated file name
        coverage report
        coverage xml
    - name: Store coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
    - name: Add coverage report to GitHub summary
      run: coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
    - name: Fail if coverage is below 100%
      run: coverage report --fail-under=100
